### ISSUE TITLE
您好，我运行之后发现exportExcel2003不能正常运行

### ISSUE THREAD

**Issue by xiaqingweb** [T5750/poi#1]
如题。一直转圈，没有异常

**Comment by T5750** [comment]
你好，是不是JOptionPane弹出框没有点确定？或者，断点调试下 @xiaqingweb

**Comment by kevinblue** [comment]
我点击链接的时候出现500错误

**Comment by T5750** [comment]
点击链接出现500错误的具体报错信息贴下 @kevinblue

**Comment by kevinblue** [comment]
HTTP Status 500 - Error instantiating servlet class test.ReadExcelServlet
type Exception report
message Error instantiating servlet class test.ReadExcelServlet

description The server encountered an internal error that prevented it from fulfilling this request.
exception
javax.servlet.ServletException: Error instantiating servlet class test.ReadExcelServlet
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Unknown Source)
root cause

**Comment by kevinblue** [comment]
我启动后点击超链接就报这种错误

**Comment by T5750** [comment]
有没有类似java.lang.ClassNotFoundException这样的异常？可以从配置web.xml，项目代码结构着手调试；或者参考最新代码

**Comment by kevinblue** [comment]
最新代码在哪里，还有ｂｕｉｌｄ文件夹　在ｗｅｂｃｏｎｔｅｎｔ上面，我移动到下面的时候，上面还是删除不掉

**Comment by kevinblue** [comment]
都是classnot found exception

**Comment by kevinblue** [comment]
你最新的代码在哪里？还有下载下来的额时候，缺少了httpservlet的包，我自己在网上找了一个包，javax.serlvet.jar包，也不知道是不是最初的要的包

**Comment by T5750** [comment]
工程地址 https://github.com/T5750/poi
下载地址 https://github.com/T5750/poi/archive/master.zip

**Comment by kevinblue** [comment]
thank you

**Comment by T5750** [comment]
You're welcome
