### ISSUE TITLE
报错：Text length was 22 but the last format index was 28

### ISSUE THREAD

**Issue by ChristChen128** [T5750/poi#2]
有时会出现这行代码构建的TreeMap<Integer, CTRPrElt> formats = this.getFormatMap(this.st)的最大值与原text的长度不符合，报错：
java.lang.IllegalArgumentException: Text length was 22 but the last format index was 28
 org.apache.poi.xssf.usermodel.XSSFRichTextString.buildCTRst(XSSFRichTextString.java:576) ~[poi-ooxml-3.17.jar:3.17]
 org.apache.poi.xssf.usermodel.XSSFRichTextString.applyFont(XSSFRichTextString.java:156) ~[poi-ooxml-3.17.jar:3.17]
 org.apache.poi.xssf.usermodel.XSSFRichTextString.applyFont(XSSFRichTextString.java:166) ~[poi-ooxml-3.17.jar:3.17]

**Comment by T5750** [comment]
你好，在master中，不确定是否是`ExcelExportUtil` -> `richString.applyFont(font3);`引起，我这边用poi 3.17并未重现。
参照[issue2](https://github.com/T5750/poi/tree/issue2)这个分支试试吧。

**Comment by ChristChen128** [comment]
这个问题我是偶尔才会出现，是在对微信的openID设置字体的时候出现的异常，大部分openID都是正常的，2万个中出现了一个异常，try catch做了处理，就是觉得有些奇怪，居然会不一样

**Comment by ChristChen128** [comment]
异常的值是o9qAGtxS7K25ItIvnNXd_xBcCe_0

**Comment by T5750** [comment]
Excel 2007中，调用了`XSSFRichTextString.utfDecode()`。有两种解决方法：
1. [TestExportExcel](https://github.com/T5750/poi/blob/issue2/src/test/java/t5750/poi/export/TestExportExcel.java) -> `exportExcelWithStyle()`，然后Excel 2003转2007
2. [TestExportExcel2007](https://github.com/T5750/poi/blob/issue2/src/test/java/t5750/poi/export/TestExportExcel2007.java) -> `export2007WithStyle()`

**Comment by ChristChen128** [comment]
好的，谢谢

**Comment by T5750** [comment]
不用谢
