### ISSUE TITLE
只引入poi 5.0版本还显示3.17 和5.0.0 都有，方法和实现类都走的3.17 是什么原因呢

### ISSUE THREAD

**Issue by Yan-minghao** [T5750/poi#4]
<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.0.0</version>
		</dependency>
![image](https://user-images.githubusercontent.com/33973209/138217854-1f3c170d-35b6-4d20-b8b9-4b1a2276c492.png)

**Comment by T5750** [comment]
POI 5.x 分支 https://github.com/T5750/poi
POI 3.x 分支 https://github.com/T5750/poi/tree/poi3
需要时再打开
